import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Barlow } from "next/font/google";
import "./globals.css";
import Header from "./Header"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
  variable: "--font-barlow", // Nome da variável que o Tailwind v4 vai ler
});

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="pt-BR">
      <body className={`${barlow.variable} font-sans bg-slate-950 text-white min-h-screen`}>
        
        {/* 2. IMPORTANTE: Coloque o seu Header bem aqui */}
        <Header />

        {/* O 'children' representa o conteúdo do seu page.tsx */}
        <main >
          {children}
        </main>

      </body>
    </html>
  );
}
